//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface CookerPrx extends SmartDevicePrx
{
    default CookerInfo getInfo()
    {
        return getInfo(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CookerInfo getInfo(java.util.Map<String, String> context)
    {
        return _iceI_getInfoAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CookerInfo> getInfoAsync()
    {
        return _iceI_getInfoAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CookerInfo> getInfoAsync(java.util.Map<String, String> context)
    {
        return _iceI_getInfoAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CookerInfo> _iceI_getInfoAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CookerInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getInfo", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     CookerInfo ret;
                     ret = CookerInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void putOnBurner(int burnerNumber)
        throws BurnerOccupied,
               InvalidBurnerNumber
    {
        putOnBurner(burnerNumber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void putOnBurner(int burnerNumber, java.util.Map<String, String> context)
        throws BurnerOccupied,
               InvalidBurnerNumber
    {
        try
        {
            _iceI_putOnBurnerAsync(burnerNumber, context, true).waitForResponseOrUserEx();
        }
        catch(BurnerOccupied ex)
        {
            throw ex;
        }
        catch(InvalidBurnerNumber ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> putOnBurnerAsync(int burnerNumber)
    {
        return _iceI_putOnBurnerAsync(burnerNumber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> putOnBurnerAsync(int burnerNumber, java.util.Map<String, String> context)
    {
        return _iceI_putOnBurnerAsync(burnerNumber, context, false);
    }

    /**
     * @hidden
     * @param iceP_burnerNumber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_putOnBurnerAsync(int iceP_burnerNumber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "putOnBurner", null, sync, _iceE_putOnBurner);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_burnerNumber);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_putOnBurner =
    {
        BurnerOccupied.class,
        InvalidBurnerNumber.class
    };

    default void getFromBurner(int burnerNumber)
    {
        getFromBurner(burnerNumber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void getFromBurner(int burnerNumber, java.util.Map<String, String> context)
    {
        _iceI_getFromBurnerAsync(burnerNumber, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> getFromBurnerAsync(int burnerNumber)
    {
        return _iceI_getFromBurnerAsync(burnerNumber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> getFromBurnerAsync(int burnerNumber, java.util.Map<String, String> context)
    {
        return _iceI_getFromBurnerAsync(burnerNumber, context, false);
    }

    /**
     * @hidden
     * @param iceP_burnerNumber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_getFromBurnerAsync(int iceP_burnerNumber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFromBurner", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_burnerNumber);
                 }, null);
        return f;
    }

    default void putInOven()
        throws CookerDontHaveOven,
               OvenOccupied
    {
        putInOven(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void putInOven(java.util.Map<String, String> context)
        throws CookerDontHaveOven,
               OvenOccupied
    {
        try
        {
            _iceI_putInOvenAsync(context, true).waitForResponseOrUserEx();
        }
        catch(CookerDontHaveOven ex)
        {
            throw ex;
        }
        catch(OvenOccupied ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> putInOvenAsync()
    {
        return _iceI_putInOvenAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> putInOvenAsync(java.util.Map<String, String> context)
    {
        return _iceI_putInOvenAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_putInOvenAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "putInOven", null, sync, _iceE_putInOven);
        f.invoke(true, context, null, null, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_putInOven =
    {
        CookerDontHaveOven.class,
        OvenOccupied.class
    };

    default void getFromOven()
        throws CookerDontHaveOven
    {
        getFromOven(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void getFromOven(java.util.Map<String, String> context)
        throws CookerDontHaveOven
    {
        try
        {
            _iceI_getFromOvenAsync(context, true).waitForResponseOrUserEx();
        }
        catch(CookerDontHaveOven ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> getFromOvenAsync()
    {
        return _iceI_getFromOvenAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> getFromOvenAsync(java.util.Map<String, String> context)
    {
        return _iceI_getFromOvenAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_getFromOvenAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFromOven", null, sync, _iceE_getFromOven);
        f.invoke(true, context, null, null, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getFromOven =
    {
        CookerDontHaveOven.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CookerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), CookerPrx.class, _CookerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CookerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), CookerPrx.class, _CookerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CookerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), CookerPrx.class, _CookerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CookerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), CookerPrx.class, _CookerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static CookerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, CookerPrx.class, _CookerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static CookerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, CookerPrx.class, _CookerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default CookerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (CookerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default CookerPrx ice_adapterId(String newAdapterId)
    {
        return (CookerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default CookerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (CookerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default CookerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (CookerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default CookerPrx ice_invocationTimeout(int newTimeout)
    {
        return (CookerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default CookerPrx ice_connectionCached(boolean newCache)
    {
        return (CookerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default CookerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (CookerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CookerPrx ice_secure(boolean b)
    {
        return (CookerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default CookerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (CookerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CookerPrx ice_preferSecure(boolean b)
    {
        return (CookerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default CookerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (CookerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default CookerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (CookerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default CookerPrx ice_collocationOptimized(boolean b)
    {
        return (CookerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default CookerPrx ice_twoway()
    {
        return (CookerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default CookerPrx ice_oneway()
    {
        return (CookerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default CookerPrx ice_batchOneway()
    {
        return (CookerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default CookerPrx ice_datagram()
    {
        return (CookerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default CookerPrx ice_batchDatagram()
    {
        return (CookerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default CookerPrx ice_compress(boolean co)
    {
        return (CookerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default CookerPrx ice_timeout(int t)
    {
        return (CookerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default CookerPrx ice_connectionId(String connectionId)
    {
        return (CookerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default CookerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (CookerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::Cooker";
    }
}
