//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public enum CookerTypes implements java.io.Serializable
{
    NOOVEN2BURNERS(0),
    NOOVEN4BURNERS(1),
    NOOVEN6BURNERS(2),
    HASOVEN4BURNERS(3),
    HASOVEN6BURNERS(4);

    public int value()
    {
        return _value;
    }

    public static CookerTypes valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return NOOVEN2BURNERS;
        case 1:
            return NOOVEN4BURNERS;
        case 2:
            return NOOVEN6BURNERS;
        case 3:
            return HASOVEN4BURNERS;
        case 4:
            return HASOVEN6BURNERS;
        }
        return null;
    }

    private CookerTypes(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 4);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, CookerTypes v)
    {
        if(v == null)
        {
            ostr.writeEnum(SmartHome.CookerTypes.NOOVEN2BURNERS.value(), 4);
        }
        else
        {
            ostr.writeEnum(v.value(), 4);
        }
    }

    public static CookerTypes ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(4);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CookerTypes> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CookerTypes v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<CookerTypes> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static CookerTypes validate(int v)
    {
        final CookerTypes e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
