//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

/**
 * Helper class for marshaling/unmarshaling Devices.
 **/
public final class DevicesHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, SmartDeviceInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                SmartDeviceInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static SmartDeviceInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final SmartDeviceInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(3);
        v = new SmartDeviceInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = SmartDeviceInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SmartDeviceInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, SmartDeviceInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            DevicesHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<SmartDeviceInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            SmartDeviceInfo[] v;
            v = DevicesHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
