//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface KettlePrx extends SmartDevicePrx
{
    default KettleInfo getInfo()
    {
        return getInfo(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default KettleInfo getInfo(java.util.Map<String, String> context)
    {
        return _iceI_getInfoAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<KettleInfo> getInfoAsync()
    {
        return _iceI_getInfoAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<KettleInfo> getInfoAsync(java.util.Map<String, String> context)
    {
        return _iceI_getInfoAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<KettleInfo> _iceI_getInfoAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<KettleInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getInfo", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     KettleInfo ret;
                     ret = KettleInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void putWater(Water water)
        throws KettleOverflow
    {
        putWater(water, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void putWater(Water water, java.util.Map<String, String> context)
        throws KettleOverflow
    {
        try
        {
            _iceI_putWaterAsync(water, context, true).waitForResponseOrUserEx();
        }
        catch(KettleOverflow ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> putWaterAsync(Water water)
    {
        return _iceI_putWaterAsync(water, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> putWaterAsync(Water water, java.util.Map<String, String> context)
    {
        return _iceI_putWaterAsync(water, context, false);
    }

    /**
     * @hidden
     * @param iceP_water -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_putWaterAsync(Water iceP_water, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "putWater", null, sync, _iceE_putWater);
        f.invoke(true, context, null, ostr -> {
                     Water.ice_write(ostr, iceP_water);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_putWater =
    {
        KettleOverflow.class
    };

    default void boilWater()
        throws NotEnoughtWater
    {
        boilWater(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void boilWater(java.util.Map<String, String> context)
        throws NotEnoughtWater
    {
        try
        {
            _iceI_boilWaterAsync(context, true).waitForResponseOrUserEx();
        }
        catch(NotEnoughtWater ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> boilWaterAsync()
    {
        return _iceI_boilWaterAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> boilWaterAsync(java.util.Map<String, String> context)
    {
        return _iceI_boilWaterAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_boilWaterAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "boilWater", null, sync, _iceE_boilWater);
        f.invoke(true, context, null, null, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_boilWater =
    {
        NotEnoughtWater.class
    };

    default Water getWater(float volume)
        throws NotEnoughtWater
    {
        return getWater(volume, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Water getWater(float volume, java.util.Map<String, String> context)
        throws NotEnoughtWater
    {
        try
        {
            return _iceI_getWaterAsync(volume, context, true).waitForResponseOrUserEx();
        }
        catch(NotEnoughtWater ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Water> getWaterAsync(float volume)
    {
        return _iceI_getWaterAsync(volume, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Water> getWaterAsync(float volume, java.util.Map<String, String> context)
    {
        return _iceI_getWaterAsync(volume, context, false);
    }

    /**
     * @hidden
     * @param iceP_volume -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Water> _iceI_getWaterAsync(float iceP_volume, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Water> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getWater", null, sync, _iceE_getWater);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeFloat(iceP_volume);
                 }, istr -> {
                     Water ret;
                     ret = Water.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getWater =
    {
        NotEnoughtWater.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static KettlePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), KettlePrx.class, _KettlePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static KettlePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), KettlePrx.class, _KettlePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static KettlePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), KettlePrx.class, _KettlePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static KettlePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), KettlePrx.class, _KettlePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static KettlePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, KettlePrx.class, _KettlePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static KettlePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, KettlePrx.class, _KettlePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default KettlePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (KettlePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default KettlePrx ice_adapterId(String newAdapterId)
    {
        return (KettlePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default KettlePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (KettlePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default KettlePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (KettlePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default KettlePrx ice_invocationTimeout(int newTimeout)
    {
        return (KettlePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default KettlePrx ice_connectionCached(boolean newCache)
    {
        return (KettlePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default KettlePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (KettlePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default KettlePrx ice_secure(boolean b)
    {
        return (KettlePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default KettlePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (KettlePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default KettlePrx ice_preferSecure(boolean b)
    {
        return (KettlePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default KettlePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (KettlePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default KettlePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (KettlePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default KettlePrx ice_collocationOptimized(boolean b)
    {
        return (KettlePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default KettlePrx ice_twoway()
    {
        return (KettlePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default KettlePrx ice_oneway()
    {
        return (KettlePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default KettlePrx ice_batchOneway()
    {
        return (KettlePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default KettlePrx ice_datagram()
    {
        return (KettlePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default KettlePrx ice_batchDatagram()
    {
        return (KettlePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default KettlePrx ice_compress(boolean co)
    {
        return (KettlePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default KettlePrx ice_timeout(int t)
    {
        return (KettlePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default KettlePrx ice_connectionId(String connectionId)
    {
        return (KettlePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default KettlePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (KettlePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::Kettle";
    }
}
