//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface ManageSystemPrx extends com.zeroc.Ice.ObjectPrx
{
    default SmartDeviceInfo[] getDevicesList()
    {
        return getDevicesList(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default SmartDeviceInfo[] getDevicesList(java.util.Map<String, String> context)
    {
        return _iceI_getDevicesListAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<SmartDeviceInfo[]> getDevicesListAsync()
    {
        return _iceI_getDevicesListAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<SmartDeviceInfo[]> getDevicesListAsync(java.util.Map<String, String> context)
    {
        return _iceI_getDevicesListAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<SmartDeviceInfo[]> _iceI_getDevicesListAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<SmartDeviceInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getDevicesList", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     SmartDeviceInfo[] ret;
                     ret = DevicesHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void addKettle(KettleTypes kettleType, String description)
    {
        addKettle(kettleType, description, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addKettle(KettleTypes kettleType, String description, java.util.Map<String, String> context)
    {
        _iceI_addKettleAsync(kettleType, description, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addKettleAsync(KettleTypes kettleType, String description)
    {
        return _iceI_addKettleAsync(kettleType, description, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addKettleAsync(KettleTypes kettleType, String description, java.util.Map<String, String> context)
    {
        return _iceI_addKettleAsync(kettleType, description, context, false);
    }

    /**
     * @hidden
     * @param iceP_kettleType -
     * @param iceP_description -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addKettleAsync(KettleTypes iceP_kettleType, String iceP_description, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addKettle", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     KettleTypes.ice_write(ostr, iceP_kettleType);
                     ostr.writeString(iceP_description);
                 }, null);
        return f;
    }

    default void addBulbulator(String description)
    {
        addBulbulator(description, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addBulbulator(String description, java.util.Map<String, String> context)
    {
        _iceI_addBulbulatorAsync(description, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addBulbulatorAsync(String description)
    {
        return _iceI_addBulbulatorAsync(description, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addBulbulatorAsync(String description, java.util.Map<String, String> context)
    {
        return _iceI_addBulbulatorAsync(description, context, false);
    }

    /**
     * @hidden
     * @param iceP_description -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addBulbulatorAsync(String iceP_description, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addBulbulator", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_description);
                 }, null);
        return f;
    }

    default void addStove(StoveFuel fuelType, String description)
    {
        addStove(fuelType, description, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addStove(StoveFuel fuelType, String description, java.util.Map<String, String> context)
    {
        _iceI_addStoveAsync(fuelType, description, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addStoveAsync(StoveFuel fuelType, String description)
    {
        return _iceI_addStoveAsync(fuelType, description, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addStoveAsync(StoveFuel fuelType, String description, java.util.Map<String, String> context)
    {
        return _iceI_addStoveAsync(fuelType, description, context, false);
    }

    /**
     * @hidden
     * @param iceP_fuelType -
     * @param iceP_description -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addStoveAsync(StoveFuel iceP_fuelType, String iceP_description, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addStove", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     StoveFuel.ice_write(ostr, iceP_fuelType);
                     ostr.writeString(iceP_description);
                 }, null);
        return f;
    }

    default void addCooker(CookerTypes cookerType, String description)
    {
        addCooker(cookerType, description, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addCooker(CookerTypes cookerType, String description, java.util.Map<String, String> context)
    {
        _iceI_addCookerAsync(cookerType, description, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addCookerAsync(CookerTypes cookerType, String description)
    {
        return _iceI_addCookerAsync(cookerType, description, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addCookerAsync(CookerTypes cookerType, String description, java.util.Map<String, String> context)
    {
        return _iceI_addCookerAsync(cookerType, description, context, false);
    }

    /**
     * @hidden
     * @param iceP_cookerType -
     * @param iceP_description -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addCookerAsync(CookerTypes iceP_cookerType, String iceP_description, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addCooker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     CookerTypes.ice_write(ostr, iceP_cookerType);
                     ostr.writeString(iceP_description);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageSystemPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ManageSystemPrx.class, _ManageSystemPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageSystemPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ManageSystemPrx.class, _ManageSystemPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageSystemPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ManageSystemPrx.class, _ManageSystemPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManageSystemPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ManageSystemPrx.class, _ManageSystemPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ManageSystemPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ManageSystemPrx.class, _ManageSystemPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ManageSystemPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ManageSystemPrx.class, _ManageSystemPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ManageSystemPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ManageSystemPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ManageSystemPrx ice_adapterId(String newAdapterId)
    {
        return (ManageSystemPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ManageSystemPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ManageSystemPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ManageSystemPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ManageSystemPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ManageSystemPrx ice_invocationTimeout(int newTimeout)
    {
        return (ManageSystemPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ManageSystemPrx ice_connectionCached(boolean newCache)
    {
        return (ManageSystemPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ManageSystemPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ManageSystemPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ManageSystemPrx ice_secure(boolean b)
    {
        return (ManageSystemPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ManageSystemPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ManageSystemPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ManageSystemPrx ice_preferSecure(boolean b)
    {
        return (ManageSystemPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ManageSystemPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ManageSystemPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ManageSystemPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ManageSystemPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ManageSystemPrx ice_collocationOptimized(boolean b)
    {
        return (ManageSystemPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ManageSystemPrx ice_twoway()
    {
        return (ManageSystemPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ManageSystemPrx ice_oneway()
    {
        return (ManageSystemPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ManageSystemPrx ice_batchOneway()
    {
        return (ManageSystemPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ManageSystemPrx ice_datagram()
    {
        return (ManageSystemPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ManageSystemPrx ice_batchDatagram()
    {
        return (ManageSystemPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ManageSystemPrx ice_compress(boolean co)
    {
        return (ManageSystemPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ManageSystemPrx ice_timeout(int t)
    {
        return (ManageSystemPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ManageSystemPrx ice_connectionId(String connectionId)
    {
        return (ManageSystemPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ManageSystemPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ManageSystemPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::ManageSystem";
    }
}
