//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class StoveInfo implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public StoveFuel fuelType;

    public float fuelLevel;

    public StoveInfo()
    {
        this.fuelType = StoveFuel.CORAL;
    }

    public StoveInfo(StoveFuel fuelType, float fuelLevel)
    {
        this.fuelType = fuelType;
        this.fuelLevel = fuelLevel;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        StoveInfo r = null;
        if(rhs instanceof StoveInfo)
        {
            r = (StoveInfo)rhs;
        }

        if(r != null)
        {
            if(this.fuelType != r.fuelType)
            {
                if(this.fuelType == null || r.fuelType == null || !this.fuelType.equals(r.fuelType))
                {
                    return false;
                }
            }
            if(this.fuelLevel != r.fuelLevel)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SmartHome::StoveInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fuelType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fuelLevel);
        return h_;
    }

    public StoveInfo clone()
    {
        StoveInfo c = null;
        try
        {
            c = (StoveInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        StoveFuel.ice_write(ostr, this.fuelType);
        ostr.writeFloat(this.fuelLevel);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.fuelType = StoveFuel.ice_read(istr);
        this.fuelLevel = istr.readFloat();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, StoveInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public StoveInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        StoveInfo v = new StoveInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<StoveInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, StoveInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<StoveInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(StoveInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final StoveInfo _nullMarshalValue = new StoveInfo();

    /** @hidden */
    public static final long serialVersionUID = -299513993815488282L;
}
