//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class Water implements java.lang.Cloneable,
                              java.io.Serializable
{
    public float volume;

    public float temperature;

    public Water()
    {
    }

    public Water(float volume, float temperature)
    {
        this.volume = volume;
        this.temperature = temperature;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Water r = null;
        if(rhs instanceof Water)
        {
            r = (Water)rhs;
        }

        if(r != null)
        {
            if(this.volume != r.volume)
            {
                return false;
            }
            if(this.temperature != r.temperature)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SmartHome::Water");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, volume);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, temperature);
        return h_;
    }

    public Water clone()
    {
        Water c = null;
        try
        {
            c = (Water)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeFloat(this.volume);
        ostr.writeFloat(this.temperature);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.volume = istr.readFloat();
        this.temperature = istr.readFloat();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Water v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Water ice_read(com.zeroc.Ice.InputStream istr)
    {
        Water v = new Water();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Water> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Water v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(8);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Water> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Water.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Water _nullMarshalValue = new Water();

    /** @hidden */
    public static final long serialVersionUID = -9208001190959855892L;
}
